[build]
rustflags = [
    "-W", "missing_docs",
]
incremental = true

[env]
LLVM_SYS_191_PREFIX = { value = "./target-llvm/target-final/", relative = true, force = false }

[tools.clippy]
warn = [
    "missing_docs_in_private_items",
]
