name: Build and test

on:
  pull_request:
  push:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:

  # Cargo checks
  cargo-check:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/matter-labs/zksync-llvm-runner:latest
    steps:
      - uses: actions/checkout@v4
      - name: Cargo checks
        uses: matter-labs/era-compiler-ci/.github/actions/cargo-check@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}

  # Build and run regression tests
  build-and-test:
    runs-on: matterlabs-ci-runner-high-performance
    container:
      image: ghcr.io/matter-labs/zksync-llvm-runner:latest
    env:
      TARGET: x86_64-unknown-linux-gnu
      LLVM_SYS_170_PREFIX: "${{ github.workspace }}/target-llvm/target-final"
    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Build LLVM
        uses: matter-labs/era-compiler-ci/.github/actions/build-llvm@v1
        with:
          build-type: 'RelWithDebInfo'
          enable-assertions: true

      - name: Run tests
        uses: matter-labs/era-compiler-ci/.github/actions/rust-unit-tests@v1
        with:
          target: ${{ env.TARGET }}
          enable-coverage: ${{ github.event_name == 'push' }}
          coverage-token: ${{ secrets.CODECOV_TOKEN }}

  # Special job that allows some of the jobs to be skipped or failed
  # requiring others to be successful
  pr-checks:
    runs-on: ubuntu-latest
    if: always()
    needs:
      - cargo-check
      - build-and-test
    steps:
      - name: Decide on PR checks
        uses: re-actors/alls-green@release/v1
        with:
          jobs: ${{ toJSON(needs) }}
