name: License and secrets check

on:
  pull_request:
  push:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:

  # Cargo checks
  cargo-check:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/matter-labs/zksync-llvm-runner:latest
    steps:
      - uses: actions/checkout@v4
      - name: Cargo checks
        uses: matter-labs/era-compiler-ci/.github/actions/cargo-check@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}

  # Check for secrets leak in the repository
  secrets-scanner:
    uses: matter-labs/era-compiler-ci/.github/workflows/secrets-scanner.yaml@main
    secrets: inherit
